config/routes.rb
Rails.application.routes.draw do
  resources :devices
  resources :business_priorities

end

app/models/business_priority.rb
class BusinessPriority < ActiveRecord::Base
  has_and_belongs_to_many :devices
end

app/models/device.rb
class Device < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/business_priorities_controller.rb
class BusinessPrioritiesController < ApplicationController
  before_action :set_business_priority, only: [:show, :edit, :update, :destroy]

  # GET /business_priorities
  # GET /business_priorities.json
  def index
    @business_priorities = BusinessPriority.all
  end

  # GET /business_priorities/1
  # GET /business_priorities/1.json
  def show
  end

  # GET /business_priorities/new
  def new
    @business_priority = BusinessPriority.new
  end

  # GET /business_priorities/1/edit
  def edit
  end

  # POST /business_priorities
  # POST /business_priorities.json
  def create
    @business_priority = BusinessPriority.new(business_priority_params)

    respond_to do |format|
      if @business_priority.save
        format.html { redirect_to @business_priority, notice: 'Business priority was successfully created.' }
        format.json { render :show, status: :created, location: @business_priority }
      else
        format.html { render :new }
        format.json { render json: @business_priority.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /business_priorities/1
  # PATCH/PUT /business_priorities/1.json
  def update
    respond_to do |format|
      if @business_priority.update(business_priority_params)
        format.html { redirect_to @business_priority, notice: 'Business priority was successfully updated.' }
        format.json { render :show, status: :ok, location: @business_priority }
      else
        format.html { render :edit }
        format.json { render json: @business_priority.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /business_priorities/1
  # DELETE /business_priorities/1.json
  def destroy
    @business_priority.destroy
    respond_to do |format|
      format.html { redirect_to business_priorities_url, notice: 'Business priority was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_business_priority
      @business_priority = BusinessPriority.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def business_priority_params
      params.require(:business_priority).permit(:rule_name, { device_ids: [] })
    end
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  before_action :set_device, only: [:show, :edit, :update, :destroy]

  # GET /devices
  # GET /devices.json
  def index
    @devices = Device.all
  end

  # GET /devices/1
  # GET /devices/1.json
  def show
  end

  # GET /devices/new
  def new
    @device = Device.new
  end

  # GET /devices/1/edit
  def edit
  end

  # POST /devices
  # POST /devices.json
  def create
    @device = Device.new(device_params)

    respond_to do |format|
      if @device.save
        format.html { redirect_to @device, notice: 'Device was successfully created.' }
        format.json { render :show, status: :created, location: @device }
      else
        format.html { render :new }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /devices/1
  # PATCH/PUT /devices/1.json
  def update
    respond_to do |format|
      if @device.update(device_params)
        format.html { redirect_to @device, notice: 'Device was successfully updated.' }
        format.json { render :show, status: :ok, location: @device }
      else
        format.html { render :edit }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /devices/1
  # DELETE /devices/1.json
  def destroy
    @device.destroy
    respond_to do |format|
      format.html { redirect_to devices_url, notice: 'Device was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_device
      @device = Device.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def device_params
      params[:device]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/business_priorities_helper.rb
module BusinessPrioritiesHelper
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/views/business_priorities/_form.html.erb
<%= form_for(@business_priority) do |f| %>
  <% if @business_priority.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@business_priority.errors.count, "error") %> prohibited this business_priority from being saved:</h2>

      <ul>
      <% @business_priority.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :rule_name %><br>
    <%= f.text_field :rule_name %>
  </div>
  
  
  <div class="field form-group row">
    <%= f.label :devices, class: "col-sm-2" %>
    <div class="col-sm-10">
      <%= f.collection_check_boxes( :device_ids, Device.all, :id, :id, {}, {:class => 'form-control'} )  %>
    </div>
  </div>
  
  
  
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/business_priorities/edit.html.erb
<h1>Editing Business Priority</h1>

<%= render 'form' %>

<%= link_to 'Show', @business_priority %> |
<%= link_to 'Back', business_priorities_path %>

app/views/business_priorities/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Business Priorities</h1>

<table>
  <thead>
    <tr>
      <th>Rule name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @business_priorities.each do |business_priority| %>
      <tr>
        <td><%= business_priority.rule_name %></td>
        <td><%= link_to 'Show', business_priority %></td>
        <td><%= link_to 'Edit', edit_business_priority_path(business_priority) %></td>
        <td><%= link_to 'Destroy', business_priority, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Business priority', new_business_priority_path %>

app/views/business_priorities/new.html.erb
<h1>New Business Priority</h1>

<%= render 'form' %>

<%= link_to 'Back', business_priorities_path %>

app/views/business_priorities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Rule name:</strong>
  <%= @business_priority.rule_name %>
</p>

<%= link_to 'Edit', edit_business_priority_path(@business_priority) %> |
<%= link_to 'Back', business_priorities_path %>

app/views/devices/_form.html.erb
<%= form_for(@device) do |f| %>
  <% if @device.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@device.errors.count, "error") %> prohibited this device from being saved:</h2>

      <ul>
      <% @device.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/devices/edit.html.erb
<h1>Editing Device</h1>

<%= render 'form' %>

<%= link_to 'Show', @device %> |
<%= link_to 'Back', devices_path %>

app/views/devices/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Devices</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @devices.each do |device| %>
      <tr>
        <td><%= link_to 'Show', device %></td>
        <td><%= link_to 'Edit', edit_device_path(device) %></td>
        <td><%= link_to 'Destroy', device, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Device', new_device_path %>

app/views/devices/new.html.erb
<h1>New Device</h1>

<%= render 'form' %>

<%= link_to 'Back', devices_path %>

app/views/devices/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_device_path(@device) %> |
<%= link_to 'Back', devices_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Formdemo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>